/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* Generated By:JJTree: Do not edit this line. AstDeferredExpression.java */

//Copyright (C) 2012 Potix Corporation. All Rights Reserved.
//History: Tue, Sep 18, 2012  10:34:09 AM
// Author: hernichen
//Port from Tomcat 7.0.x (java -> dart)



/**
 * @author Jacob Hookom [jacob@hookom.net]
 * @version $Id: AstDeferredExpression.java 939311 2010-04-29 14:01:02Z kkolinko $
 */
class AstDeferredExpression extends SimpleNode {
    AstDeferredExpression(int id)
        : super(id);

    //@Override
    ClassMirror getType(EvaluationContext ctx) {
        return this.children_[0].getType(ctx);
    }

    //@Override
    Object getValue(EvaluationContext ctx) {
        return this.children_[0].getValue(ctx);
    }

    //@Override
    bool isReadOnly(EvaluationContext ctx) {
        return this.children_[0].isReadOnly(ctx);
    }

    //@Override
    void setValue(EvaluationContext ctx, Object value) {
        this.children_[0].setValue(ctx, value);
    }
}
