/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* Generated By:JJTree: Do not edit this line. AstDotSuffix.java */

//Copyright (C) 2012 Potix Corporation. All Rights Reserved.
//History: Tue, Sep 18, 2012  10:47:30 AM
// Author: hernichen
//Port from Tomcat 7.0.x (java -> dart)

/**
 * $Id: AstMethodParameters.java 899450 2010-01-14 22:41:41Z markt $
 */
class AstMethodParameters extends SimpleNode {
    AstMethodParameters(int id)
        : super(id);

    List<Object> getParameters(EvaluationContext ctx) {
        List<Object> params = new List();
        for (int i = 0; i < this.jjtGetNumChildren(); i++) {
            params.add(this.jjtGetChild(i).getValue(ctx));
        }
        return params;
    }
    
    List<ClassMirror> getParameterTypes(EvaluationContext ctx) {
        List<ClassMirror> paramTypes = new List();
        for (int i = 0; i < this.jjtGetNumChildren(); i++) {
            paramTypes.add(this.jjtGetChild(i).getType(ctx));
        }
        return paramTypes;
    }
}
