/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* Generated By:JJTree: Do not edit this line. AstFunction.java */

//Copyright (C) 2012 Potix Corporation. All Rights Reserved.
//History: Tue, Sep 18, 2012  10:00:01 AM
// Author: hernichen
//Port from Tomcat 7.0.x (java -> dart)

/**
 * @author Jacob Hookom [jacob@hookom.net]
 * @version $Id: AstFunction.java 1201570 2011-11-14 01:38:18Z kkolinko $
 */
class AstFunction extends SimpleNode {

    String localName_ = "";

    String prefix_ = "";

    AstFunction(int id)
        : super(id);

    String getLocalName() {
        return localName_;
    }

    String getOutputName() {
        if (this.prefix_ == null) {
            return this.localName_;
        } else {
            return "${this.prefix_}:${this.localName_}";
        }
    }

    String getPrefix() {
        return prefix_;
    }

    //@Override
    ClassMirror getType(EvaluationContext ctx) {

        FunctionMapper fnMapper = ctx.getFunctionMapper();

        // quickly validate again for this request
        if (fnMapper == null) {
            throw new ELException(MessageFactory.getString("error.fnMapper.null"));
        }
        Function fn = fnMapper.resolveFunction(this.prefix_, this.localName_);
        MethodMirror m = (reflect(fn) as ClosureMirror).function;
        if (m == null) {
            throw new ELException(MessageFactory.getString("error.fnMapper.method",
                    [this.getOutputName()]));
        }
        return ClassUtil.getCorrespondingClassMirror(m.returnType);
    }

    //@Override
    Object getValue(EvaluationContext ctx) {

        FunctionMapper fnMapper = ctx.getFunctionMapper();

        // quickly validate again for this request
        if (fnMapper == null) {
            throw new ELException(MessageFactory.getString("error.fnMapper.null"));
        }
        Function fn = fnMapper.resolveFunction(this.prefix_, this.localName_);
        MethodMirror m = (reflect(fn) as ClosureMirror).function;
        if (m == null) {
            throw new ELException(MessageFactory.getString("error.fnMapper.method",
                    [this.getOutputName()]));
        }

        List values = null;
        int numParams = this.jjtGetNumChildren(); //TODO(henri): namedArgs not supported yet
        if (numParams > 0) {
            values = new List(numParams);
            try {
                for (int i = 0; i < numParams; i++) {
                    values[i] = this.children_[i].getValue(ctx);
                }
            } on ELException catch (ele) {
                throw new ELException(MessageFactory.getString("error.function", [this
                        .getOutputName()]), ele);
            }
        } else {
          values = new List(0);
        }
        List params = ELSupport.convertArgs(values, m, this);

        Object result = ClassUtil.apply(fn, params);
//        try {
//            result = m.invoke(null, params);
//        } on IllegalAccessException catch (iae) {
//            throw new ELException(MessageFactory.getString("error.function", [this
//                    .getOutputName()]), iae);
//        } on InvocationTargetException catch (ite) {
//            Throwable cause = ite.getCause();
//            throw new ELException(MessageFactory.getString("error.function", [this
//                    .getOutputName()]), cause);
//        }
        return result;
    }

    void setLocalName(String localName) {
        this.localName_ = localName;
    }

    void setPrefix(String prefix) {
        this.prefix_ = prefix;
    }


    //@Override
    String toString()
    {
        return "${ELParserTreeConstants.jjtNodeName[id_]}[${this.getOutputName()}]";
    }
}
