/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* Generated By:JJTree: Do not edit this line. AstInteger.java */

//Copyright (C) 2012 Potix Corporation. All Rights Reserved.
//History: Mon, Sep 17, 2012  07:29:05 PM
// Author: hernichen
//Port from Tomcat 7.0.x (java -> dart)

/**
 * @author Jacob Hookom [jacob@hookom.net]
 * @version $Id: AstInteger.java 1003861 2010-10-02 18:53:30Z markt $
 */
class AstInteger extends SimpleNode {
    AstInteger(int id)
        : super(id);

    num _number;

    num getInteger_() {
        if (this._number == null) {
            this._number = int.parse(this.image_);
        }
        return _number;
    }

    //@Override
    ClassMirror getType(EvaluationContext ctx) {
        return ClassUtil.INT_MIRROR;
    }

    //@Override
    Object getValue(EvaluationContext ctx) {
        return this.getInteger_();
    }
}
