/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* Generated By:JJTree: Do not edit this line. AstString.java */

//Copyright (C) 2012 Potix Corporation. All Rights Reserved.
//History: Tue, Sep 18, 2012  09:50:51 AM
// Author: hernichen
//Port from Tomcat 7.0.x (java -> dart)

/**
 * @author Jacob Hookom [jacob@hookom.net]
 * @version $Id: AstString.java 1003861 2010-10-02 18:53:30Z markt $
 */
class AstString extends SimpleNode {
    AstString(int id)
        : super(id);

    String _str;

    String getString() {
        if (this._str == null) {
            this._str = this.image_.substring(1, this.image_.length - 1);
        }
        return this._str;
    }

    //@Override
    ClassMirror getType(EvaluationContext ctx) {
        return ClassUtil.STRING_MIRROR;
    }

    //@Override
    Object getValue(EvaluationContext ctx) {
        return this.getString();
    }

    //@Override
    void setImage(String image) {
        if (image.indexOf('\\') == -1) {
            this.image_ = image;
            return;
        }
        int size = image.length;
        StringBuffer buf = new StringBuffer();
        for (int i = 0; i < size; i++) {
            String c = image.substring(i, i+1);
            if (c == '\\' && i + 1 < size) {
                String c1 = image.substring(i+1, i+2);
                if (c1 == '\\' || c1 == '"' || c1 == '\'') {
                    c = c1;
                    i++;
                }
            }
            buf.add(c);
        }
        this.image_ = buf.toString();
    }
}
